<?xml version="1.0" encoding="utf-8"?><Database Name="Pet_Store" Class="DatosPetStoreDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=Pet_Store;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Pet_StoreConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.cita" Member="citas">
    <Type Name="cita">
      <Column Name="id_cita" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="hora" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_cliente" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.ctsCargarCitas" Method="ctsCargarCitas">
    <ElementType Name="ctsCargarCitasResult">
      <Column Name="id_cita" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="hora" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_cliente" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>