//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCRWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class bitacora_login
    {
        public int Id_Bitacora { get; set; }
        public string correo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> hora { get; set; }
        public Nullable<int> status { get; set; }
    }
}
