//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCRWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class consulta
    {
        public int Id_consulta { get; set; }
        public Nullable<int> id_cita { get; set; }
        public Nullable<int> Id_Venta { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
        public Nullable<int> id_mascota { get; set; }
    
        public virtual cita cita { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual mascota mascota { get; set; }
        public virtual venta venta { get; set; }
    }
}
