//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCRWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Pet_StoreEntities : DbContext
    {
        public Pet_StoreEntities()
            : base("name=Pet_StoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bitacora_login> bitacora_login { get; set; }
        public virtual DbSet<cita> citas { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<consulta> consultas { get; set; }
        public virtual DbSet<empleado> empleadoes { get; set; }
        public virtual DbSet<mascota> mascotas { get; set; }
        public virtual DbSet<venta> ventas { get; set; }
    }
}
