#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetsCR
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Pet_Store")]
	public partial class DatosPetStoreDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcita(cita instance);
    partial void Updatecita(cita instance);
    partial void Deletecita(cita instance);
    #endregion
		
		public DatosPetStoreDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Pet_StoreConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatosPetStoreDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatosPetStoreDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatosPetStoreDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatosPetStoreDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<cita> citas
		{
			get
			{
				return this.GetTable<cita>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ctsCargarCitas")]
		public ISingleResult<ctsCargarCitasResult> ctsCargarCitas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ctsCargarCitasResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cita")]
	public partial class cita : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_cita;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<int> _hora;
		
		private System.Nullable<int> _Id_cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_citaChanging(int value);
    partial void Onid_citaChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OnhoraChanging(System.Nullable<int> value);
    partial void OnhoraChanged();
    partial void OnId_clienteChanging(System.Nullable<int> value);
    partial void OnId_clienteChanged();
    #endregion
		
		public cita()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cita", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_cita
		{
			get
			{
				return this._id_cita;
			}
			set
			{
				if ((this._id_cita != value))
				{
					this.Onid_citaChanging(value);
					this.SendPropertyChanging();
					this._id_cita = value;
					this.SendPropertyChanged("id_cita");
					this.Onid_citaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora", DbType="Int")]
		public System.Nullable<int> hora
		{
			get
			{
				return this._hora;
			}
			set
			{
				if ((this._hora != value))
				{
					this.OnhoraChanging(value);
					this.SendPropertyChanging();
					this._hora = value;
					this.SendPropertyChanged("hora");
					this.OnhoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_cliente", DbType="Int")]
		public System.Nullable<int> Id_cliente
		{
			get
			{
				return this._Id_cliente;
			}
			set
			{
				if ((this._Id_cliente != value))
				{
					this.OnId_clienteChanging(value);
					this.SendPropertyChanging();
					this._Id_cliente = value;
					this.SendPropertyChanged("Id_cliente");
					this.OnId_clienteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class ctsCargarCitasResult
	{
		
		private int _id_cita;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<int> _hora;
		
		private System.Nullable<int> _Id_cliente;
		
		public ctsCargarCitasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cita", DbType="Int NOT NULL")]
		public int id_cita
		{
			get
			{
				return this._id_cita;
			}
			set
			{
				if ((this._id_cita != value))
				{
					this._id_cita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora", DbType="Int")]
		public System.Nullable<int> hora
		{
			get
			{
				return this._hora;
			}
			set
			{
				if ((this._hora != value))
				{
					this._hora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_cliente", DbType="Int")]
		public System.Nullable<int> Id_cliente
		{
			get
			{
				return this._Id_cliente;
			}
			set
			{
				if ((this._Id_cliente != value))
				{
					this._Id_cliente = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
